version: '3.1'

services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    environment:
      POSTGRES_USER: missionbase
      POSTGRES_PASSWORD: MissionBaseD3vT3mp
    volumes:
      - ./.data/local_pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: themaster5.07@gmail.com
      PGADMIN_DEFAULT_PASSWORD: MissionBaseD3vT3mp

volumes:
  local_pgdata: